### PR TITLE
[chore] Add missing docstrings

### PR DESCRIPTION
**Pull request by nwithan8**
# Description

- Add missing docstrings for Hooks

# Testing

- No changes to functionality or compatibility, all unit tests pass as expected

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

### CODE REVIEW

**Review by Justintime50 — CHANGES_REQUESTED** [review]
Love the changes, but there are way too many to review in a single diff even if all are cosmetic. Mind breaking this up into smaller PRs focusing only on one thing at a time (spacing, changing sentences, etc) or batching 3-4 types of objects together?

**Comment by nwithan8** [comment]
The README changes have been rolled back for now.

Only one change was made globally, the format of the namespace. However, that kicked the indention of everything over by one tab, so it touched nearly every line. It seems the diff viewer is struggling to match lines and it makes it looks like more things got changed that actually did. If you look at the commits individually, you can better see what happened.

**Review by Justintime50 — COMMENTED** [review]
I'd like the indentation stuff separated out from the changes to content please. If there was a PR that was just indentation, that'd be an easy approve. As it stands, there's 12k lines to look at which just isn't feasible knowing there is content changes mixed in. If you can break them out separately, the indentation is an easy one on its own and the content changes can then be reviewed in-depth without all the noise.

**Comment by nwithan8** [comment]
The minor docstring updates have been reverted temporarily. The only active changes in this PR now are indention formatting.

**Comment by Justintime50** [comment]
Unless I've got a weird caching issue, I'm still seeing lots of content changes here

**Comment by nwithan8** [comment]
> However, that kicked the indention of everything over by one tab, so it touched nearly every line. It seems the diff viewer is struggling to match lines and it makes it looks like more things got changed that actually did.

**Comment by Justintime50** [comment]
If that's the case, I can't in good conscience move on with reviewing this - it's just too much noise. I'd suggest batching these into a few files at a time to get it closer to the 1k lines or something much smaller if these indentation changes are that important.

**Comment by nwithan8** [comment]
This PR has been updated to only be:
- README cleanup
- Docstring additions

**Review by jchen293 — APPROVED** [review]

**Review by Justintime50 — APPROVED** [review]
docs for days 🚀

**Review by Justintime50 — APPROVED** [review]

**Pull request merged**
