### PR TITLE
Added ability to pass a carrier param to address.Verify.

### PR DESCRIPTION
**Pull request by sawyer**

### CODE REVIEW

**Comment by jmalatia** [comment]
What are the options for the carrier param in address.Verify?  Only usps seems to work?  is UPS an option?

**Comment by att14** [comment]
The only other available carrier is Fedex currently.

**Comment by jmalatia** [comment]
Is this documented anywhere?  As I also see other things in the code that aren't in the API docs at easypost.com.

**Comment by att14** [comment]
Anything that is not documented currently is pre-release and added on a customer request basis. If you have any feature requests, not relating to this client library, feel free to email support@easypost.com.

**Pull request merged**
