### PR TITLE
Adding project for .NET Core support

### PR DESCRIPTION
**Pull request by btoles**
I'm seeing an issue with the IntelliSense, otherwise all is working fine.  Hoping I could get some direction or could hand it off to resolve this issue!  :)

image

### CODE REVIEW

**Comment by claytondus** [comment]
This should target netstandard2.0, as a class library, for the broadest compatibility.

**Comment by att14** [comment]
I'll try to land this in the next few days.

**Comment by jmwoo** [comment]
any update on this? I would love to use it in my .net core app

**Comment by btoles** [comment]
We've ended up writing an internal library to communicate with the EasyPost API as we also needed async/await support.  I should probably abandon this PR but I would contact EasyPost to see if they have plans to add .NET Core support.  It looks like@att14 has it on his radar.

**Comment by att14** [comment]
closing in favor of #113

**Pull request closed without merging**
