### PR TITLE
.Net Core 2.0 Support

### PR DESCRIPTION
**Pull request by att14**
@MazdaRacerBoy I was able to get this to work, however the dependencies do not install automatically when you install EasyPost-Official. Do you have any ideas?

### CODE REVIEW

**Comment by att14** [comment]
CC @jmwoo

**Comment by jmwoo** [comment]
I had to untick `sign the assembly`. In order to build it after getting this error:

`Unable to get MD5 checksum for the key file "EasyPost.pfx". Could not find file '\easypost-csharp\EasyPost.NetCore20\EasyPost.pfx'.`

I also replaced RestSharp.Signed with RestSharp since it's RestSharp.Signed is now obsolete:
https://github.com/restsharp/RestSharp

So far so good.

**Comment by kgrvr** [comment]
What's the ETA of merging this to master?

**Comment by att14** [comment]
Hey, sorry for the delay on this. I'll release a new version tomorrow morning PT.

**Pull request merged**
