### PR TITLE
Upgrade .net standard 2.0

### PR DESCRIPTION
**Pull request by waynebrantley**
This cleans up the project and produces a .net 4.5.2, 4.6.1 and .net standard 2.0 compatible nuget package.

Simply running dotnet pack from the easypost folder will create it.

If anyone uses something before 4.5.2 will need to use the old releases.

### CODE REVIEW

**Comment by waynebrantley** [comment]
@att14 have a look at this.  Can you review/accept and release a new version?

**Comment by joshlrogers** [comment]
There are two PR's awaiting approval and merging that make this library compatible with NetStandard 2.0.  Could we please get one of them merged in and a NuGet package released?

**Comment by Justintime50** [comment]
This is a large breaking change that I'm not sure we'd want to incorporate. We'd also need this PR rebased to properly view the diff.

**Comment by Justintime50** [comment]
Closing due to inactivity, also not a huge fan of the breaking change on older version.

**Pull request closed without merging**
