### PR TITLE
Add `commercial_invoice_letterhead` option

### PR DESCRIPTION
**Pull request by chamby**
Fixes EasyPost/easypost-csharp#142

### CODE REVIEW

**Review by Justintime50 — APPROVED** [review]
LFTM

**Comment by chamby** [comment]
@Justintime50 Sorry to bother you. Can you advocate to get this merged?

**Comment by Justintime50** [comment]
Hey @chamby, merging shouldn't be a problem; however, we currently don't have a rock-solid releasing process to get this merged code out via a new version. I'll dig into that though and hopefully have some more info soon. Thanks for your patience.

In the interim, you could definitely build from source and use your local copy with your changes until we've released a new version containing this PR.

**Review by ajnassar — APPROVED** [review]

**Review by ejachang — APPROVED** [review]
looks good to me as well

**Review by Sarahbear1926 — APPROVED** [review]

**Review by jontsai — APPROVED** [review]

**Comment by Justintime50** [comment]
@chamby thanks for the PR! We've merged this in. This will be included in the next release of this library. We don't yet have an ETA on when that will be but are currently working on it.

**Pull request merged**
