### PR TITLE
add basic github workflow using dotnet 2.2.*

### PR DESCRIPTION
**Pull request by Roguelazer**
will this work? who knows!

### CODE REVIEW

**Comment by jontsai** [comment]
Is the failing build still a concern? Otherwise, I'm down to merge this to try it out, and iterate from there.

**Comment by Justintime50** [comment]
It's failing because we target 3-4 different SDK's in the build and this GitHub Action is only using 1. We'll need to configure it right to get it to pass.

This is part something I've been chipping away at, didn't work on macOS with Mono but should work on Windows.

**Comment by Roguelazer** [comment]
Now that github supports windows instances for Actions, we should be able to build this with the native SDKs.

**Comment by epclee** [comment]
No longer needed. Closing.

**Comment by nwithan8** [comment]
Handled by #186

**Pull request closed without merging**
