### PR TITLE
Upgrade RestSharp to 106.12.0

### LINKED ISSUE #147: RestSharp compatibility
We are using the EasyPost .Net Core libraries. The library is incompatible with newer versions of RestSharp. Will you be adding support? The latest version is 106.11.2, but the EasyPost libraries are only compatible with 106.4.2.

### PR DESCRIPTION
**Pull request by davitgr**
Upgrade RestSharp to version 106.12.0.

Closes #147

### CODE REVIEW

**Comment by davitgr** [comment]
@att14 Can you please take a look at this PR when you have a chance? Thank you.

**Comment by davitgr** [comment]
@att14 has anybody had a chance to look at this PR? It's been a while since I created it.

**Comment by davitgr** [comment]
@Justintime50 can you please look into what I should do to get this merged? I've had this PR open for a really long time now.

**Comment by Justintime50** [comment]
@davitgr thanks for submitting this PR! We are currently determining our releasing strategy for this client library so we can get these open PR's merged and a new version released. I don't have a solid ETA to provide; however, we are looking into it at the moment. In the meantime, you can certainly build the project from source with your changes until we are able to incorporate these in a new release. Thanks for your patience!

**Comment by davitgr** [comment]
@Justintime50 is this PR going to be merged into the upcoming release?

**Comment by Justintime50** [comment]
Hey @davitgr, thanks for following up. We are looking to bump this internally most likely in the next couple weeks to include in a future release. We'll either be incorporating your change here or including it elsewhere as a part of our other efforts for the next release. I'll keep you posted when I have more info.

**Comment by davitgr** [comment]
Thank you @Justintime50 . Recently, the older versions were flagged as a security vulnerability in one of our security scans.

**Comment by Justintime50** [comment]
Ah, good to know! Yeah, this is definitely something we want to be addressing shortly.

**Comment by Justintime50** [comment]
Hey @davitgr, it looks like dependabot opened #165, #166, and #167 that does the same thing. I'd love to take your PR since you put in the work and have been asking about this; however, I noticed that those PRs from dependabot don't update the version tag in a few places yours does, specifically on the tags that have a `PublicKeyToken` listed. Would love to have your thoughts?

**Comment by davitgr** [comment]
Hi @Justintime50. My PR covers the unit test project, and also as you mentioned, the places that have a `PublicToken` listed. The changes I made built in Visual Studio, and the nuget package manager made the changes when I chose to upgrade the RestSharp version. I feel confident in my changes.

**Review by Justintime50 — APPROVED** [review]
Thanks for the added info! My only concern would be that the PublicToken is tied to version `106.4.2.0` of RestSharp and would also need to be updated. If it built correctly though, that's good enough for me. We can always adjust tokens if needed.

**Review by jontsai — APPROVED** [review]

**Review by Sarahbear1926 — APPROVED** [review]

**Pull request merged**
